-- MySQL Script generated by MySQL Workbench
-- 12/16/14 22:05:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema easykit
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema easykit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `easykit` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `easykit` ;

-- -----------------------------------------------------
-- Table `easykit`.`ek_medias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easykit`.`ek_medias` (
  `medias_id` INT(11) NOT NULL AUTO_INCREMENT,
  `medias_file` VARCHAR(255) NOT NULL,
  `medias_type` VARCHAR(45) NULL,
  `medias_created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`medias_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easykit`.`ek_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easykit`.`ek_users` (
  `users_id` INT(11) NOT NULL AUTO_INCREMENT,
  `users_email` VARCHAR(45) NOT NULL,
  `users_password` VARCHAR(45) NOT NULL,
  `users_firstname` VARCHAR(45) NULL,
  `users_lastname` VARCHAR(45) NULL,
  `users_birth` DATE NULL,
  `users_created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `users_updated_at` TIMESTAMP NULL,
  `users_medias_id` INT(11) NULL DEFAULT 1,
  PRIMARY KEY (`users_id`, `users_medias_id`),
  UNIQUE INDEX `users_email_UNIQUE` (`users_email` ASC),
  INDEX `fk_ek_users_ek_medias1_idx` (`users_medias_id` ASC),
  CONSTRAINT `fk_ek_users_ek_medias1`
    FOREIGN KEY (`users_medias_id`)
    REFERENCES `easykit`.`ek_medias` (`medias_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easykit`.`ek_events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easykit`.`ek_events` (
  `events_id` INT(11) NOT NULL AUTO_INCREMENT,
  `events_name` VARCHAR(255) NOT NULL,
  `events_description` TEXT NULL,
  `events_starttime` DATETIME NOT NULL,
  `events_endtime` DATETIME NOT NULL,
  `events_geox` VARCHAR(45) NULL,
  `events_geoy` VARCHAR(45) NULL,
  `events_created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `events_users_id` INT(11) NOT NULL,
  PRIMARY KEY (`events_id`),
  INDEX `fk_events_users1_idx` (`events_users_id` ASC),
  CONSTRAINT `fk_events_users1`
    FOREIGN KEY (`events_users_id`)
    REFERENCES `easykit`.`ek_users` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easykit`.`ek_events_medias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easykit`.`ek_events_medias` (
  `events_medias_events_id` INT(11) NOT NULL,
  `events_medias_medias_id` INT(11) NOT NULL,
  `events_medias_name` VARCHAR(255) NULL,
  `events_medias_description` TEXT NULL,
  `events_medias_created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`events_medias_events_id`, `events_medias_medias_id`),
  INDEX `fk_events_has_medias_medias1_idx` (`events_medias_medias_id` ASC),
  INDEX `fk_events_has_medias_events1_idx` (`events_medias_events_id` ASC),
  CONSTRAINT `fk_events_has_medias_events1`
    FOREIGN KEY (`events_medias_events_id`)
    REFERENCES `easykit`.`ek_events` (`events_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_has_medias_medias1`
    FOREIGN KEY (`events_medias_medias_id`)
    REFERENCES `easykit`.`ek_medias` (`medias_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easykit`.`ek_moneypots`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easykit`.`ek_moneypots` (
  `moneypots_id` INT(11) NOT NULL AUTO_INCREMENT,
  `moneypots_events_id` INT(11) NOT NULL,
  `moneypost_users_id` INT(11) NOT NULL,
  `moneypots_name` VARCHAR(255) NOT NULL,
  `moneypots_description` VARCHAR(255) NULL,
  `moneypots_reached` FLOAT NULL,
  `moneypots_endtime` DATETIME NOT NULL,
  `moneypots_created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`moneypots_id`, `moneypots_events_id`, `moneypost_users_id`),
  INDEX `fk_events_has_users_users1_idx` (`moneypost_users_id` ASC),
  INDEX `fk_events_has_users_events1_idx` (`moneypots_events_id` ASC),
  CONSTRAINT `fk_events_has_users_events1`
    FOREIGN KEY (`moneypots_events_id`)
    REFERENCES `easykit`.`ek_events` (`events_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_has_users_users1`
    FOREIGN KEY (`moneypost_users_id`)
    REFERENCES `easykit`.`ek_users` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easykit`.`ek_mails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easykit`.`ek_mails` (
  `mails_id` INT(11) NOT NULL AUTO_INCREMENT,
  `mails_moneypot_id` INT(11) NOT NULL,
  `mails_users_id` INT(11) NOT NULL,
  `mails_content` TEXT NOT NULL,
  `mails_created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`mails_id`, `mails_moneypot_id`, `mails_users_id`),
  INDEX `fk_moneypot_has_users_users1_idx` (`mails_users_id` ASC),
  INDEX `fk_moneypot_has_users_moneypot1_idx` (`mails_moneypot_id` ASC),
  CONSTRAINT `fk_moneypot_has_users_moneypot1`
    FOREIGN KEY (`mails_moneypot_id`)
    REFERENCES `easykit`.`ek_moneypots` (`moneypots_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_moneypot_has_users_users1`
    FOREIGN KEY (`mails_users_id`)
    REFERENCES `easykit`.`ek_users` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easykit`.`ek_steps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easykit`.`ek_steps` (
  `steps_id` INT(11) NOT NULL AUTO_INCREMENT,
  `steps_moneypots_id` INT(11) NOT NULL,
  `steps_name` VARCHAR(45) NULL,
  `steps_goal` FLOAT NULL,
  PRIMARY KEY (`steps_id`, `steps_moneypots_id`),
  INDEX `fk_steps_moneypots1_idx` (`steps_moneypots_id` ASC),
  CONSTRAINT `fk_steps_moneypots1`
    FOREIGN KEY (`steps_moneypots_id`)
    REFERENCES `easykit`.`ek_moneypots` (`moneypots_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easykit`.`ek_payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easykit`.`ek_payments` (
  `payments_id` INT(11) NOT NULL AUTO_INCREMENT,
  `payments_moneypots_id` INT(11) NOT NULL,
  `payments_users_id` INT(11) NOT NULL,
  `payments_amount` FLOAT NOT NULL,
  `payments_created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`payments_id`, `payments_moneypots_id`, `payments_users_id`),
  INDEX `fk_moneypots_has_users_users1_idx` (`payments_users_id` ASC),
  INDEX `fk_moneypots_has_users_moneypots1_idx` (`payments_moneypots_id` ASC),
  CONSTRAINT `fk_moneypots_has_users_moneypots1`
    FOREIGN KEY (`payments_moneypots_id`)
    REFERENCES `easykit`.`ek_moneypots` (`moneypots_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_moneypots_has_users_users1`
    FOREIGN KEY (`payments_users_id`)
    REFERENCES `easykit`.`ek_users` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easykit`.`ek_payments_has_steps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easykit`.`ek_payments_has_steps` (
  `payments_has_steps_payments_id` INT(11) NOT NULL,
  `steps_steps_id` INT(11) NOT NULL,
  PRIMARY KEY (`payments_has_steps_payments_id`, `steps_steps_id`),
  INDEX `fk_payments_has_steps_steps1_idx` (`steps_steps_id` ASC),
  INDEX `fk_payments_has_steps_payments1_idx` (`payments_has_steps_payments_id` ASC),
  CONSTRAINT `fk_payments_has_steps_payments1`
    FOREIGN KEY (`payments_has_steps_payments_id`)
    REFERENCES `easykit`.`ek_payments` (`payments_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payments_has_steps_steps1`
    FOREIGN KEY (`steps_steps_id`)
    REFERENCES `easykit`.`ek_steps` (`steps_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easykit`.`ek_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easykit`.`ek_admin` (
  `admin_id` INT(11) NOT NULL AUTO_INCREMENT,
  `admin_username` VARCHAR(45) NOT NULL,
  `admin_password` VARCHAR(255) NOT NULL,
  `admin_email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`admin_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easykit`.`ek_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easykit`.`ek_tokens` (
  `tokens_id` INT(11) NOT NULL AUTO_INCREMENT,
  `tokens_token` VARCHAR(45) NULL,
  `tokens_device` VARCHAR(255) NULL,
  `tokens_disabled` TINYINT(1) NULL,
  `tokens_users_id` INT(11) NOT NULL,
  PRIMARY KEY (`tokens_id`, `tokens_users_id`),
  INDEX `fk_ek_tokens_ek_users1_idx` (`tokens_users_id` ASC),
  CONSTRAINT `fk_ek_tokens_ek_users1`
    FOREIGN KEY (`tokens_users_id`)
    REFERENCES `easykit`.`ek_users` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
